eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
server:
  port: 6095
  
spring:
  application:
    name: HELP-SERVICE