
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
            
        - id: help-service
          uri: lb://HELP-SERVICE
          predicates:
            - Path=/help/**
            
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/** 
           
  

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
server:
  port: 8989
  
